### ISSUE TITLE
Examples codes in wiki page does not exist

### ISSUE THREAD

**Issue by kaskavalci** [eYSIP-2016/Object-Tracking-Camera#1]
https://github.com/eYSIP-2016/Object-Tracking-Camera/wiki/Other-Algorithms page refers to `Extra Modules` folder in the repository but that folder does not exist.

example: [Matrioska Tracker](https://github.com/eYSIP-2016/Object-Tracking-Camera/tree/master/Extra%20modules/Matrioska%20Tracker)

**Comment by nikitaporje** [comment]
Thank you for such a grate project. Its very useful to me.
Source code for tracking is not exist. Can you please make it available

**Comment by AbhishekRathore311** [comment]
Because of some problem links given on your given link are not working.
you can find codes on the following link
https://github.com/eYSIP-2016/Object-Tracking-Camera/tree/master/Other%20Algorithms(Object%20Tracking)

**Comment by AbhishekRathore311** [comment]
You can find different codes on following links
https://github.com/eYSIP-2016/Object-Tracking-Camera/tree/master/Tutorials/4.%20Object%20Tracking%20(Based%20on%20ROI)%20and%20Re-recognizing%20the%20object%20if%20it%20escapes%20and%20comes%20back%20into%20the%20frame

https://github.com/eYSIP-2016/Object-Tracking-Camera/tree/master/Other%20Algorithms(Object%20Tracking)

And if you will explore whole project, you will find many codes. Pjoject
link is following
https://github.com/eYSIP-2016/Object-Tracking-Camera

On the following link we have given codes with tutorial
https://github.com/eYSIP-2016/Object-Tracking-Camera/tree/master/Tutorials

And thank you for appreciation.

**Comment by nikitaporje** [comment]
Thank you for your support !!

**Comment by peymanrostami** [comment]
you should be proud of yourself for this grate project

**Comment by AbhishekRathore311** [comment]
Thanl you peymanrostami
